services:
  - type: web
    name: notification-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: KAFKA_ENABLED
        value: "false"
      - key: DB_URL
        sync: false
      - key: REDIS_HOST
        fromService:
          type: redis
          name: notification-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: notification-redis
          property: port
      - key: REDIS_URL
        fromService:
          type: redis
          name: notification-redis
          property: connectionString
      - key: REDIS_SSL_ENABLED
        value: false
      - key: API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://notification-system.onrender.com

  - type: redis
    name: notification-redis
    ipAllowList: []
    plan: free
